/**
 * Voice trade e2e — real whisper.cpp through the QVAC sidecar.
 *
 * Skipped end-to-end when the whisper model isn't on disk
 * (QVAC_WHISPER_MODEL_PATH unset). When it is, we feed a checked-in WAV
 * generated by macOS `say` ("buy 0.1 SOL with USDC on Solana"), transcribe
 * it, and assert the transcript contains the substantive keywords.
 *
 * Whisper is non-deterministic on punctuation and casing, so assertions
 * use case-insensitive substring checks on words it shouldn't drop.
 */

import { test, describe, after } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

process.env.TELEGRAM_BOT_TOKEN ??= 'test_token';
process.env.ZERION_API_KEY ??= 'test_key';

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURE = join(__dirname, 'fixtures', 'swap-sol-usdc.wav');

const HAS_MODEL = !!process.env.QVAC_WHISPER_MODEL_PATH
  && existsSync(process.env.QVAC_WHISPER_MODEL_PATH);
const HAS_FIXTURE = existsSync(FIXTURE);

describe('QVAC voice trade — sidecar transcription', { skip: !HAS_MODEL || !HAS_FIXTURE }, () => {
  after(async () => {
    const { shutdownSidecar } = await import('../../../engine/qvac/sidecar/client.mjs');
    await shutdownSidecar();
  });

  test('transcribes a real "swap SOL → USDC" voice clip', async () => {
    const { createTranscriber } = await import('../../../engine/qvac/transcription.mjs');
    const t = await createTranscriber();
    try {
      const audio = readFileSync(FIXTURE);
      const result = await t.transcribe(audio, { language: 'en' });
      const text = (result.text || '').toLowerCase();
      // Fixture says "buy zero point one S O L with U S D C on Solana".
      // We assert on the tokens that whisper-tiny.en is reliable on. The
      // first word ("buy") is unreliable because macOS `say` produces
      // prosody that whisper-tiny sometimes hears as "high"/"hi" — a
      // real-world TTS-vs-STT mismatch. The substantive keywords land
      // consistently.
      assert.ok(text.length > 0, `transcript should be non-empty, got: "${result.text}"`);
      const keywords = ['sol', 'usdc', 'solana'];
      for (const kw of keywords) {
        assert.ok(text.includes(kw), `transcript should contain "${kw}", got: "${result.text}"`);
      }
      // And it should not contain timestamp markers (the sidecar strips them).
      assert.ok(!/<\|/.test(result.text), `transcript should not contain timestamp markers, got: "${result.text}"`);
    } finally {
      await t.unload();
    }
  });
});
