import assert from "node:assert/strict";
import { describe, it, before, after } from "node:test";
import { getKeypair } from '../../engine/lib/keypair.mjs';
import { createEventBus } from '../../engine/core/event-bus.mjs';
import { DipBuyerStrategy } from '../../engine/strategies/dip-buyer.mjs';
import { TakeProfitStrategy } from '../../engine/strategies/take-profit.mjs';
import { RebalancerStrategy } from '../../engine/strategies/rebalancer.mjs';
import { PriceMonitor } from '../../engine/monitors/price.mjs';
import { PortfolioMonitor } from '../../engine/monitors/portfolio.mjs';
import { addAlert, getAlerts, clearAlerts } from '../../engine/store/plans.mjs';
import { 
  createRealTestEnvironment,
  setupRealTestEnv,
  runPreflightChecks,
  waitForReal,
  REAL_E2E_CONFIG 
} from './real-setup.mjs';

describe("E2E: Signal-Reactive Automation (Real)", () => {
  let testEnv, restoreEnv, keypair, eventBus, priceMonitor, portfolioMonitor;
  let dipBuyerStrategy, takeProfitStrategy, rebalancerStrategy;
  const TEST_WALLET_ADDRESS = 'test-wallet-address';
  const TEST_CHAT_ID = 123456789;

  before(async () => {
    console.log('[E2E SIGNALS] Setting up real signal automation test environment...');
    
    // Create test environment
    testEnv = await createRealTestEnvironment();
    restoreEnv = setupRealTestEnv(testEnv.testDir);
    
    // Get real keypair
    keypair = getKeypair();
    
    // Run preflight checks
    await runPreflightChecks(keypair);
    
    // Create real event bus
    eventBus = createEventBus();
    
    // Initialize real monitors with actual API calls
    priceMonitor = new PriceMonitor({
      eventBus,
      interval: 5000, // 5 second intervals for testing
      tokens: ['SOL', 'USDC']
    });
    
    portfolioMonitor = new PortfolioMonitor({
      eventBus,
      walletAddress: TEST_WALLET_ADDRESS,
      interval: 10000, // 10 second intervals for testing
      zerionApiKey: process.env.ZERION_API_KEY
    });
    
    // Initialize real strategies
    const notifyFn = (message) => console.log(`[E2E SIGNALS] Notification: ${message}`);
    
    dipBuyerStrategy = new DipBuyerStrategy({
      eventBus,
      walletName: 'test-wallet',
      notifyFn
    });
    
    takeProfitStrategy = new TakeProfitStrategy({
      eventBus, 
      walletName: 'test-wallet',
      notifyFn
    });
    
    rebalancerStrategy = new RebalancerStrategy({
      eventBus,
      walletName: 'test-wallet',
      notifyFn
    });
    
    // Clear any existing alerts
    clearAlerts();
    
    console.log('[E2E SIGNALS] Real signal automation test environment ready');
  });

  after(async () => {
    // Stop all monitors and strategies
    if (priceMonitor) priceMonitor.stop();
    if (portfolioMonitor) portfolioMonitor.stop();
    if (dipBuyerStrategy) dipBuyerStrategy.stop();
    if (takeProfitStrategy) takeProfitStrategy.stop();
    if (rebalancerStrategy) rebalancerStrategy.stop();
    
    if (testEnv) testEnv.cleanup();
    if (restoreEnv) restoreEnv();
  });

  it("validates real price monitoring and signal generation", async () => {
    // Start real price monitor
    priceMonitor.start();
    
    // Wait for at least one price update
    let priceSignalReceived = false;
    const unsubscribe = eventBus.subscribe('PRICE_UPDATE', (signal) => {
      priceSignalReceived = true;
      console.log(`[E2E SIGNALS] ✅ Price signal received: ${signal.token} = $${signal.price} (${signal.change24h > 0 ? '+' : ''}${signal.change24h.toFixed(2)}%)`);
    });
    
    // Wait for real price data
    await waitForReal(
      () => priceSignalReceived,
      30000, // 30 second timeout
      1000   // Check every second
    );
    
    assert.equal(priceSignalReceived, true, 'Should receive real price signals');
    unsubscribe();
    
    console.log(`[E2E SIGNALS] ✅ Real price monitoring validated`);
  });

  it("tests real dip buying strategy with price signals", async () => {
    // Create a dip alert
    const dipAlert = {
      id: `dip-${Date.now()}`,
      type: 'price_dip',
      token: 'SOL',
      threshold: 5, // 5% dip
      amount: REAL_E2E_CONFIG.TEST_TRADE_AMOUNT, // $0.50
      chain: 'solana',
      chatId: TEST_CHAT_ID,
      status: 'active',
      createdAt: Date.now()
    };
    
    addAlert(dipAlert);
    
    // Start dip buyer strategy
    dipBuyerStrategy.start();
    
    // Listen for trade proposals generated by dip buyer
    let tradeProposalReceived = false;
    const unsubscribe = eventBus.subscribe('TRADE_PROPOSAL', (proposal) => {
      if (proposal.strategyType === 'dip-buyer') {
        tradeProposalReceived = true;
        assert.equal(proposal.toToken, 'SOL', 'Dip buy should target SOL');
        assert.ok(proposal.reason.includes('dip'), 'Reason should mention dip');
        console.log(`[E2E SIGNALS] ✅ Dip buyer proposal: ${proposal.amount} ${proposal.fromToken} → ${proposal.toToken}`);
      }
    });
    
    // Simulate a price dip signal
    const dipSignal = {
      type: 'PRICE_DIP',
      token: 'SOL',
      currentPrice: 142.50,
      previousPrice: 150.00,
      changePercent: -5.0,
      timestamp: Date.now()
    };
    
    eventBus.emit('PRICE_DIP', dipSignal);
    
    // Wait for strategy response
    await waitForReal(
      () => tradeProposalReceived,
      10000, // 10 second timeout
      500    // Check every 500ms
    );
    
    assert.equal(tradeProposalReceived, true, 'Should generate trade proposal from dip signal');
    unsubscribe();
    
    console.log(`[E2E SIGNALS] ✅ Dip buying strategy validated`);
  });

  it("tests real portfolio monitoring and rebalancing signals", async () => {
    // Only test if we have a real wallet address with actual portfolio
    if (!process.env.TEST_WALLET_ADDRESS) {
      console.log('[E2E SIGNALS] Skipping portfolio monitoring - TEST_WALLET_ADDRESS not set');
      return;
    }
    
    // Set target allocation for rebalancing
    const targetAllocation = {
      'SOL': 60,  // 60%
      'USDC': 40  // 40%
    };
    
    rebalancerStrategy.setTargetAllocation(targetAllocation);
    rebalancerStrategy.start();
    
    // Start portfolio monitor with real wallet
    const realPortfolioMonitor = new PortfolioMonitor({
      eventBus,
      walletAddress: process.env.TEST_WALLET_ADDRESS,
      interval: 5000,
      zerionApiKey: process.env.ZERION_API_KEY
    });
    
    realPortfolioMonitor.start();
    
    // Wait for portfolio data
    let portfolioSignalReceived = false;
    const unsubscribe = eventBus.subscribe('PORTFOLIO_UPDATE', (signal) => {
      portfolioSignalReceived = true;
      console.log(`[E2E SIGNALS] ✅ Portfolio signal: Total value $${signal.totalValue}, ${Object.keys(signal.positions).length} positions`);
    });
    
    await waitForReal(
      () => portfolioSignalReceived,
      30000, // 30 second timeout for API calls
      2000   // Check every 2 seconds
    );
    
    assert.equal(portfolioSignalReceived, true, 'Should receive portfolio signals from real API');
    unsubscribe();
    realPortfolioMonitor.stop();
    
    console.log(`[E2E SIGNALS] ✅ Portfolio monitoring validated`);
  });

  it("validates take profit strategy with price spike signals", async () => {
    // Create a take profit alert
    const takeProfitAlert = {
      id: `tp-${Date.now()}`,
      type: 'take_profit',
      token: 'SOL',
      threshold: 10, // 10% gain
      amount: REAL_E2E_CONFIG.TEST_TRADE_AMOUNT,
      chain: 'solana',
      chatId: TEST_CHAT_ID,
      status: 'active',
      createdAt: Date.now()
    };
    
    addAlert(takeProfitAlert);
    
    // Start take profit strategy
    takeProfitStrategy.start();
    
    // Listen for take profit proposals
    let takeProfitProposalReceived = false;
    const unsubscribe = eventBus.subscribe('TRADE_PROPOSAL', (proposal) => {
      if (proposal.strategyType === 'take-profit') {
        takeProfitProposalReceived = true;
        assert.equal(proposal.fromToken, 'SOL', 'Take profit should sell SOL');
        assert.ok(proposal.reason.includes('profit'), 'Reason should mention profit');
        console.log(`[E2E SIGNALS] ✅ Take profit proposal: ${proposal.amount} ${proposal.fromToken} → ${proposal.toToken}`);
      }
    });
    
    // Simulate a price spike signal
    const spikeSignal = {
      type: 'PRICE_SPIKE',
      token: 'SOL',
      currentPrice: 165.00,
      previousPrice: 150.00,
      changePercent: 10.0,
      timestamp: Date.now()
    };
    
    eventBus.emit('PRICE_SPIKE', spikeSignal);
    
    // Wait for strategy response
    await waitForReal(
      () => takeProfitProposalReceived,
      10000,
      500
    );
    
    assert.equal(takeProfitProposalReceived, true, 'Should generate take profit proposal from spike signal');
    unsubscribe();
    
    console.log(`[E2E SIGNALS] ✅ Take profit strategy validated`);
  });

  it("tests real event bus signal routing and strategy coordination", async () => {
    // Test that multiple strategies can coexist and respond to appropriate signals
    dipBuyerStrategy.start();
    takeProfitStrategy.start();
    
    let dipSignalCount = 0;
    let spikeSignalCount = 0;
    let proposalCount = 0;
    
    // Count different signal types
    const unsubscribeDip = eventBus.subscribe('PRICE_DIP', () => dipSignalCount++);
    const unsubscribeSpike = eventBus.subscribe('PRICE_SPIKE', () => spikeSignalCount++);
    const unsubscribeProposal = eventBus.subscribe('TRADE_PROPOSAL', () => proposalCount++);
    
    // Emit multiple signals
    eventBus.emit('PRICE_DIP', {
      type: 'PRICE_DIP',
      token: 'SOL',
      currentPrice: 140,
      previousPrice: 150,
      changePercent: -6.67,
      timestamp: Date.now()
    });
    
    eventBus.emit('PRICE_SPIKE', {
      type: 'PRICE_SPIKE', 
      token: 'SOL',
      currentPrice: 170,
      previousPrice: 150,
      changePercent: 13.33,
      timestamp: Date.now() + 1000
    });
    
    // Wait for signal processing
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    assert.equal(dipSignalCount, 1, 'Should receive dip signal');
    assert.equal(spikeSignalCount, 1, 'Should receive spike signal');
    
    // Both strategies might generate proposals depending on their configuration
    console.log(`[E2E SIGNALS] Signal counts - Dips: ${dipSignalCount}, Spikes: ${spikeSignalCount}, Proposals: ${proposalCount}`);
    
    unsubscribeDip();
    unsubscribeSpike();
    unsubscribeProposal();
    
    console.log(`[E2E SIGNALS] ✅ Event bus signal routing validated`);
  });

  it("validates alert management and persistence", async () => {
    // Test alert storage and retrieval
    const initialAlerts = getAlerts(TEST_CHAT_ID);
    const initialCount = initialAlerts.length;
    
    // Create multiple alert types
    const alerts = [
      {
        id: `alert-1-${Date.now()}`,
        type: 'price_dip',
        token: 'SOL', 
        threshold: 8,
        amount: 1,
        chain: 'solana',
        chatId: TEST_CHAT_ID,
        status: 'active',
        createdAt: Date.now()
      },
      {
        id: `alert-2-${Date.now()}`,
        type: 'take_profit',
        token: 'USDC',
        threshold: 15,
        amount: 2,
        chain: 'solana',
        chatId: TEST_CHAT_ID,
        status: 'active',
        createdAt: Date.now()
      }
    ];
    
    alerts.forEach(alert => addAlert(alert));
    
    // Verify alerts were stored
    const storedAlerts = getAlerts(TEST_CHAT_ID);
    assert.equal(storedAlerts.length, initialCount + 2, 'Should have 2 additional alerts');
    
    // Verify alert data integrity
    const storedAlert1 = storedAlerts.find(a => a.id === alerts[0].id);
    assert.ok(storedAlert1, 'First alert should be found');
    assert.equal(storedAlert1.type, 'price_dip', 'Alert type should be preserved');
    assert.equal(storedAlert1.token, 'SOL', 'Alert token should be preserved');
    
    const storedAlert2 = storedAlerts.find(a => a.id === alerts[1].id);
    assert.ok(storedAlert2, 'Second alert should be found');
    assert.equal(storedAlert2.threshold, 15, 'Alert threshold should be preserved');
    
    console.log(`[E2E SIGNALS] ✅ Alert management and persistence validated`);
  });

  it("tests real Zerion API integration for portfolio monitoring", async () => {
    if (!process.env.ZERION_API_KEY || !process.env.TEST_WALLET_ADDRESS) {
      console.log('[E2E SIGNALS] Skipping Zerion API test - credentials not available');
      return;
    }
    
    const walletAddress = process.env.TEST_WALLET_ADDRESS;
    
    // Test real API call to Zerion for portfolio data
    try {
      const zerionBasicAuth = Buffer.from(`${process.env.ZERION_API_KEY}:`).toString('base64');
      const response = await fetch(`https://api.zerion.io/v1/wallets/${walletAddress}`, {
        headers: {
          'Authorization': `Basic ${zerionBasicAuth}`,
          'Content-Type': 'application/json'
        }
      });
      
      if (response.status === 404) {
        console.log('[E2E SIGNALS] Test wallet not found in Zerion (expected for new wallets)');
        return;
      }
      
      assert.ok(response.ok, `Zerion API should respond successfully: ${response.status}`);
      
      const data = await response.json();
      assert.ok(data, 'Should receive portfolio data');
      
      if (data.data && data.data.attributes) {
        const totalValue = data.data.attributes.total?.value || 0;
        console.log(`[E2E SIGNALS] ✅ Real portfolio value: $${totalValue}`);
        
        // Create a portfolio signal
        const portfolioSignal = {
          type: 'PORTFOLIO_UPDATE',
          walletAddress,
          totalValue,
          timestamp: Date.now()
        };
        
        // Emit signal to test strategy responses
        eventBus.emit('PORTFOLIO_UPDATE', portfolioSignal);
        
        // Wait for potential rebalancing proposals
        await new Promise(resolve => setTimeout(resolve, 1000));
      }
      
    } catch (err) {
      console.warn(`[E2E SIGNALS] Zerion API test failed: ${err.message}`);
    }
    
    console.log(`[E2E SIGNALS] ✅ Zerion API integration test completed`);
  });
});